export const dummyRepo = "test repo";

export const dummyContributors = [
  {
    login: "string",
    id: 0,
    avatar_url: "string",
    gravatar_id: "string",
    url: "string",
    html_url: "string",
    followers_url: "string",
    following_url: "string",
    gists_url: "string",
    starred_url: "string",
    subscriptions_url: "string",
    organizations_url: "string",
    repos_url: "string",
    events_url: "string",
    received_events_url: "string",
    type: "string",
    site_admin: false,
    contributions: 0
  }
];

export const dummyCommits = {
  all: [1, 2, 3, 4],
  owner: [1, 2, 3, 4]
};

export const dummyIssues = [
  {
    url: "string",
    repository_url: "string",
    labels_url: "string",
    comments_url: "string",
    events_url: "string",
    html_url: "string",
    id: 0,
    number: 0,
    title: "string",
    user: null,
    labels: null,
    state: "string",
    locked: false,
    assignee: null,
    assignees: null,
    comments: 0,
    created_at: new Date(),
    updated_at: new Date(),
    body: "string",
    pull_request: null
  }
];

export const dummyReepoInfo = {
  id: 0,
  name: "string",
  full_name: "string",
  owner: null,
  private: false,
  html_url: "string",
  description: "string",
  fork: false,
  url: "string",
  forks_url: "string",
  keys_url: "string",
  collaborators_url: "string",
  teams_url: "string",
  hooks_url: "string",
  issue_events_url: "string",
  events_url: "string",
  assignees_url: "string",
  branches_url: "string",
  tags_url: "string",
  blobs_url: "string",
  git_tags_url: "string",
  git_refs_url: "string",
  trees_url: "string",
  statuses_url: "string",
  languages_url: "string",
  stargazers_url: "string",
  contributors_url: "string",
  subscribers_url: "string",
  subscription_url: "string",
  commits_url: "string",
  git_commits_url: "string",
  comments_url: "string",
  issue_comment_url: "string",
  contents_url: "string",
  compare_url: "string",
  merges_url: "string",
  archive_url: "string",
  downloads_url: "string",
  issues_url: "string",
  pulls_url: "string",
  milestones_url: "string",
  notifications_url: "string",
  labels_url: "string",
  releases_url: "string",
  deployments_url: "string",
  created_at: new Date(),
  updated_at: new Date(),
  pushed_at: new Date(),
  git_url: "string",
  ssh_url: "string",
  clone_url: "string",
  svn_url: "string",
  homepage: "string",
  size: 0,
  stargazers_count: 0,
  watchers_count: 0,
  language: "string",
  has_issues: false,
  has_projects: false,
  has_downloads: false,
  has_wiki: false,
  has_pages: false,
  forks_count: 0,
  open_issues_count: 0,
  forks: 0,
  open_issues: 0,
  watchers: 0,
  default_branch: "string",
  organization: null,
  network_count: 0,
  subscribers_count: 0
};
